const bcrypt = require("bcryptjs");
const salt = bcrypt.genSaltSync(10);
const hash = bcrypt.hashSync("password", salt);

module.exports = [
  {
    name: "agatha",
    email: "agatha@gmail.com",
    passwordHash: hash,
    address: "1 Claymore Hill",
    unit: "#01-01",
    postal: "229572",
    phone: "62223888",
    role: "user",
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    name: "adna",
    email: "adna@gmail.com",
    passwordHash: hash,
    address: "1 Claymore Hill",
    unit: "#01-01",
    postal: "229572",
    phone: "62223888",
    role: "admin",
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    name: "henckels",
    email: "henckels@gmail.com",
    passwordHash: hash,
    address: "2 Claymore Hill",
    unit: "#02-02",
    postal: "229572",
    phone: "62223888",
    role: "user",
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    name: "clotilde",
    email: "clotilde@gmail.com",
    passwordHash: hash,
    address: "3 Claymore Hill",
    unit: "#3-03",
    postal: "229572",
    phone: "62223888",
    role: "user",
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    name: "dmitri",
    email: "dmitri@gmail.com",
    passwordHash: hash,
    address: "4 Claymore Hill",
    unit: "#04-04",
    postal: "229572",
    phone: "62223888",
    role: "user",
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    name: "gustave",
    email: "gustave@gmail.com",
    passwordHash: hash,
    address: "5 Claymore Hill",
    unit: "#05-05",
    postal: "229572",
    phone: "62223888",
    role: "user",
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    name: "kovacs",
    email: "kovacs@gmail.com",
    passwordHash: hash,
    address: "6 Claymore Hill",
    unit: "#06-06",
    postal: "229572",
    phone: "62223888",
    role: "user",
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    name: "olivia",
    email: "olivia@gmail.com",
    passwordHash: hash,
    address: "7 Claymore Hill",
    unit: "#07-07",
    postal: "229572",
    phone: "62223888",
    role: "user",
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    name: "timothee",
    email: "timothee@gmail.com",
    passwordHash: hash,
    address: "8 Claymore Hill",
    unit: "#08-08",
    postal: "229572",
    phone: "62223888",
    role: "user",
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    name: "suzy",
    email: "suzy@gmail.com",
    passwordHash: hash,
    address: "9 Claymore Hill",
    unit: "#09-09",
    postal: "229572",
    phone: "62223888",
    role: "user",
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    name: "lionel",
    email: "lionel@gmail.com",
    passwordHash: hash,
    address: " 10 Claymore Hill",
    unit: "#10-10",
    postal: "229572",
    phone: "62223888",
    role: "user",
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    name: "jed",
    email: "jed@gmail.com",
    passwordHash: hash,
    address: " 11 Claymore Hill",
    unit: "#11-11",
    postal: "229572",
    phone: "62223888",
    role: "user",
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    name: "becky",
    email: "becky@gmail.com",
    passwordHash: hash,
    address: " 12 Claymore Hill",
    unit: "#12-12",
    postal: "229572",
    phone: "62223888",
    role: "user",
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    name: "rudy",
    email: "rudy@gmail.com",
    passwordHash: hash,
    address: " 13 Claymore Hill",
    unit: "#13-13",
    postal: "229572",
    phone: "62223888",
    role: "user",
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    name: "edgar",
    email: "edgar@gmail.com",
    passwordHash: hash,
    address: " 14 Claymore Hill",
    unit: "#14-14",
    postal: "229572",
    phone: "62223888",
    role: "user",
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    name: "dakota",
    email: "dakota@gmail.com",
    passwordHash: hash,
    address: " 15 Claymore Hill",
    unit: "#15-15",
    postal: "229572",
    phone: "62223888",
    role: "user",
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    name: "noah",
    email: "noah@gmail.com",
    passwordHash: hash,
    address: " 16 Claymore Hill",
    unit: "#16-16",
    postal: "229572",
    phone: "62223888",
    role: "user",
    createdAt: new Date(),
    updatedAt: new Date()
  }
];
